function trackData = createPracticeTrack()
% CREATEPRACTICETRACK  AI Grand Prix practice circuit — "Club Circuit".
%
%   trackData = createPracticeTrack()
%
%   A 10-turn GP-style circuit (~480 m) with:
%     - Long start/finish straight
%     - Fast T1 sweeping right complex
%     - Technical S-curves (T2/T3)
%     - Tight chicane (T4/T5)
%     - Long back straight leading to a hairpin (T6)
%     - Sweeping return complex (T7/T8)
%     - Tight final-sector esses (T9/T10)
%
%   The track is generated by fitting a periodic cubic spline through
%   manually placed waypoints, guaranteeing a smooth closed loop.
%
%   Track width: 5 m   |   Point spacing: 0.5 m
%
%   See also: Track, practiceRace

    trackWidth = 5.0;
    res        = 0.5;

    % ------------------------------------------------------------------
    %  Circuit waypoints  [x, y]  (metres)
    %
    %  "Club Circuit" — COTA-inspired layout:
    %    ① Long SF straight (East)
    %    ② T1: sweeping right
    %    ③ T2-T9: 8-corner S-curve complex (like COTA Esses)
    %    ④ T10: tight right chicane
    %    ⑤ Back straight (West)
    %    ⑥ T11: hairpin (apex at far left)
    %    ⑦ Return: sweeping north back to SF
    %
    %  ALL y ≤ 0: track stays south of SF straight (no self-intersections).
    % ------------------------------------------------------------------
    W = [
          0,    0;   % P01  Start/Finish line
          8,   -1;   % P02  SF guide (push spline south immediately)
         60,   -3;   % P03  SF straight
         92,  -12;   % P04  T1 braking zone
        115,  -35;   % P05  T1 apex  (sweeping right)
        118,  -62;   % P06  T2 entry (S-curve start)
        105,  -80;   % P07  T2 apex  (left)
         82,  -88;   % P08  T3 apex  (right)
         68, -100;   % P09  T4 apex  (left)
         48,  -92;   % P10  T5 apex  (right)
         32, -105;   % P11  T6 apex  (left)
         14,  -95;   % P12  T7 apex  (right)
         -2, -110;   % P13  T8 apex  (left)
        -18,  -98;   % P14  T9 apex  (right)
        -32, -112;   % P15  T10 chicane (left — furthest south)
        -44,  -98;   % P16  T10 exit
        -38,  -75;   % P17  T11 hairpin approach
        -45,  -52;   % P18  T11 entry
        -48,  -30;   % P19  T11 apex  (furthest NW — actual hairpin)
        -36,  -15;   % P20  T11 exit
        -18,   -7;   % P21  return sweep
         -3,   -1;   % P22  final approach to SF
          0,    0;   % P23  close
    ];


    % ------------------------------------------------------------------
    %  Fit periodic spline through waypoints
    %  Trick: replicate a few waypoints at each end for periodic wrapping
    % ------------------------------------------------------------------
    nW   = size(W, 1) - 1;        % effective waypoints (exclude closing duplicate)
    nWrap = 4;                     % number of points to wrap at each end

    % Chord-length parameterisation of the raw waypoints
    d = sqrt(sum(diff(W(1:end-1,:), 1, 1).^2, 2));  % nW-1 chords
    d = [d; sqrt(sum((W(1,:)-W(end-1,:)).^2, 2))];   % chord from last to first
    cumChord = [0; cumsum(d)];                         % period = cumChord(end)
    period   = cumChord(end);

    % Extended (wrapped) parameter and waypoints for periodic pchip
    idxWrap  = [(nW-nWrap+1 : nW), (1:nW), (1:nWrap)];
    Wext     = W(idxWrap, :);
    tExt     = [-cumChord(end-nWrap : end-1) + (-period); ...
                 cumChord(1:nW); ...
                 cumChord(1:nWrap) + period];

    % High-resolution interpolation over one full period
    nFine = max(3000, round(period / 0.05));
    tFine = linspace(0, period, nFine + 1)';
    tFine = tFine(1:end-1);                          % half-open interval
    xFine = interp1(tExt, Wext(:,1), tFine, 'pchip');
    yFine = interp1(tExt, Wext(:,2), tFine, 'pchip');

    % ------------------------------------------------------------------
    %  Resample fine curve to uniform arc-length spacing
    % ------------------------------------------------------------------
    dsFine  = sqrt(diff(xFine).^2 + diff(yFine).^2);
    dsFine  = [dsFine; sqrt((xFine(1)-xFine(end))^2 + (yFine(1)-yFine(end))^2)];
    cumFine = [0; cumsum(dsFine)];

    nFinal = round(cumFine(end) / res);
    sUnif  = linspace(0, cumFine(end-1), nFinal)';

    % Remove any duplicate cumFine values before interpolation
    [cumFineU, ia] = unique(cumFine, 'stable');
    xFineU = [xFine; xFine(1)];
    yFineU = [yFine; yFine(1)];
    xFineU = xFineU(ia);
    yFineU = yFineU(ia);

    cx = interp1(cumFineU, xFineU, sUnif, 'pchip');
    cy = interp1(cumFineU, yFineU, sUnif, 'pchip');
    centreline = [cx, cy];

    % ------------------------------------------------------------------
    %  Tangents, normals, boundaries
    % ------------------------------------------------------------------
    N    = size(centreline, 1);
    next = mod((1:N)', N) + 1;

    tang = centreline(next,:) - centreline;
    tLen = max(sqrt(sum(tang.^2, 2)), 1e-12);
    tang = tang ./ tLen;

    normals = [-tang(:,2), tang(:,1)];    % left-pointing unit normals

    halfW         = trackWidth / 2;
    leftBoundary  = centreline + halfW * normals;
    rightBoundary = centreline - halfW * normals;

    % ------------------------------------------------------------------
    %  Cumulative arc-length along resampled centreline
    % ------------------------------------------------------------------
    segD      = sqrt(sum(diff(centreline([1:end,1],:)).^2, 2));
    cumDist   = [0; cumsum(segD(1:end-1))];
    lapLength = cumDist(end) + segD(end);

    % ------------------------------------------------------------------
    %  Start/finish line (perpendicular to centreline at index 1)
    % ------------------------------------------------------------------
    sfPt            = centreline(1,:);
    sfN             = normals(1,:);
    startFinishLine = [sfPt - halfW*sfN, sfPt + halfW*sfN];

    % ------------------------------------------------------------------
    %  Pack output
    % ------------------------------------------------------------------
    trackData.centreline      = centreline;
    trackData.width           = trackWidth;
    trackData.normals         = normals;
    trackData.leftBoundary    = leftBoundary;
    trackData.rightBoundary   = rightBoundary;
    trackData.cumDist         = cumDist;
    trackData.lapLength       = lapLength;
    trackData.startFinishLine = startFinishLine;
    trackData.startFinishIdx  = 1;
    trackData.name            = 'Club Circuit';

end
