function course = practiceTechnical(variation)
% PRACTICETECHNICAL  C2 - Technical circuit (practice version), 1 lap.
%
%   ~360 m: a chicane, two R 8 m hairpins, one R 20 m corner, three R 12 m
%   corners and short straights.  Flat.
%
%   Tests: tyres (grip in slow corners), mass, and the controller.
%
%   See also: buildPath, loadPath
    pieces = [ ...
        road.straight(20, 0, "adjust"), ...
        road.chicane(2.5, 30), ...
        road.straight(15), ...
        road.corner(8, 180, "L"), ...          % hairpin 1
        road.straight(25), ...
        road.corner(20, 90, "R"), ...
        road.straight(12, 0, "adjust"), ...
        road.corner(12, 90, "L"), ...
        road.straight(90, 0, "adjust"), ...
        road.corner(8, 180, "L"), ...          % hairpin 2
        road.straight(15), ...
        road.corner(12, 90, "R"), ...
        road.straight(20), ...
        road.corner(12, 90, "L"), ...
        road.straight(18), ...
    ];
    if nargin >= 1 && ~isempty(variation), pieces = variation(pieces); end   % instructor: hidden variations
    course = buildPath(pieces, 'Name', "Technical circuit", 'Type', "circuit", 'Laps', 1, ...
        'Width', 5, 'TimeLimit', 120);
end
