function course = practiceWet(variation)
% PRACTICEWET  A short loop with one wet patch (practice example), 1 lap.
%
%   Grip on a wet patch is between 0.6x and 0.8x the dry grip.  The wet
%   points are flagged in advance: obs.previewPoints(:,4) == 1.
%   Wet patches appear only on the unseen race-day track.
%
%   See also: buildPath, loadPath
    pieces = [ ...
        road.straight(40, 0, "adjust"), ...
        road.corner(15, 90, "L"), ...
        road.straight(30, 0, "adjust"), ...
        road.corner(15, 90, "L"), ...
        road.straight(20), ...
        road.surface(0.7, 35), ...               % wet: the next 35 m
        road.corner(10, 90, "R"), ...
        road.straight(10), ...
        road.corner(10, 90, "L"), ...
        road.straight(20, 0, "adjust"), ...
        road.corner(15, 90, "L"), ...
        road.straight(60, 0, "adjust"), ...
        road.corner(15, 90, "L"), ...
        road.straight(20), ...
    ];
    if nargin >= 1 && ~isempty(variation), pieces = variation(pieces); end   % instructor: hidden variations
    course = buildPath(pieces, 'Name', "Wet practice", 'Type', "circuit", 'Laps', 1, ...
        'Width', 5, 'TimeLimit', 90);
end
