function course = practiceMud(variation)
% PRACTICEMUD  C4 muddy road: a rally loop with three mud sections and a hill, 1 lap.
%
%   Mud (brown on the map) is slippery AND sticky: grip x 0.6 and rolling
%   resistance x 4 (road.mud).  Mud points are flagged in advance:
%   obs.previewPoints(:,4) == 1 (slippery) and obs.previewPoints(:,5) == 1 (mud).
%
%   Tests: tyres (grip against rolling loss), motor (pushing through the
%   mud), battery, and a driver that reads the surface ahead.
%
%   See also: road.mud, buildPath, loadPath
    pieces = [ ...
        road.straight(60, 0, "adjust"), ...          % start / finish
        road.corner(18, 90, "L"), ...
        road.mud(60), ...                            % mud 1: the straight into the next corner
        road.straight(45, 0, "adjust"), ...
        road.corner(18, 90, "L"), ...
        road.straight(25, 6), ...                    % climb
        road.corner(14, 90, "R"), ...                % S-bend at the top
        road.straight(15), ...
        road.corner(14, 90, "L"), ...
        road.mud(50), ...                            % mud 2: a muddy descent
        road.straight(25, -6), ...
        road.corner(18, 90, "L"), ...
        road.straight(90, 0, "adjust"), ...          % back straight
        road.mud(40), ...                            % mud 3: a muddy left-hander
        road.corner(16, 90, "L"), ...
        road.straight(20), ...
    ];
    if nargin >= 1 && ~isempty(variation), pieces = variation(pieces); end   % instructor: hidden variations
    course = buildPath(pieces, 'Name', "Muddy road", 'Type', "circuit", 'Laps', 1, ...
        'Width', 5, 'TimeLimit', 150);
end
